In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from google.colab import files

uploaded=files.upload()

Saving iris.csv to iris.csv


In [3]:
df=pd.read_csv('iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.utils import plot_model
import pydot
import graphviz

In [5]:
X=df.iloc[:,0:4].values
y=df.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
y1=enc.fit_transform(y)
Y=pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [6]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [8]:
model=Sequential()

model.add(Dense(4, input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [9]:
model.compile(optimizer="Adam", loss="categorical_crossentropy", metrics=['accuracy'])

In [11]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 2s 3ms/step - loss: 3.7675 - accuracy: 0.3083
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 3.3130 - accuracy: 0.3083
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 2.9275 - accuracy: 0.3083
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 2.5885 - accuracy: 0.3083
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 2.3261 - accuracy: 0.3083
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 2.1292 - accuracy: 0.3000
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 1.9712 - accuracy: 0.2667
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.8377 - accuracy: 0.2000
Epoch 9/100
12/12 [==============================] - 0s 3ms/step - loss: 1.7029 - accuracy: 0.1833
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.5833 - accuracy: 0.1583
Epoch 11/

In [12]:
y_pred=model.predict(X_test)
y_test_class=np.argmax(y_test, axis=1)
y_pred_class=np.argmax(y_pred, axis=1)

1/1 [==============================] - 0s 87ms/step


In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.75      0.23      0.35        13
           2       0.33      0.83      0.48         6

    accuracy                           0.63        30
   macro avg       0.69      0.69      0.61        30
weighted avg       0.76      0.63      0.61        30

[[11  0  0]
 [ 0  3 10]
 [ 0  1  5]]


In [14]:
(11+3+5)/30

0.6333333333333333